version: "3.9"

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "0.0.0.0:8000:8000"
    env_file:
          - .env
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

