# Generated by Django 4.1.1 on 2022-09-10 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def add_item(apps, schema_editor):
    Item = apps.get_model("item_payment", "Item")
    items = [
        Item(
            name=f'Item {num}',
            price=100, stripe_product_id='prod_MPbyKrmL1vJy4f',
            stripe_price_id='price_1LgmkNIV3zilNUERtP7HZsC7'
        ) for num in range(1, 4)]
    Item.objects.bulk_create(items)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('price', models.IntegerField(default=0, verbose_name='цена')),
                ('stripe_product_id', models.CharField(max_length=100)),
                ('stripe_price_id', models.CharField(max_length=100)),
                ('count', models.PositiveIntegerField(default=1, verbose_name='количество')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.RunPython(add_item),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(to='item_payment.item', verbose_name='товары')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='клиент')),
            ],
        ),
    ]
